--------------------------------------------------------
--  File created - Thursday-June-24-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View EXP_WFEX_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FMIS_DBA"."EXP_WFEX_V" ("EPOL_NAME", "ORGA_CODE", "EPIU_ID", "EINS_EINS_ID", "CODE_DISP", "EUNL_EUNL_ID", "EARD_EARD_ID", "OUIN_TYPE", "EPIU_TYPE", "CODE_NAME", "ETEX_ETEX_ID", "PHAS_TYPE", "PHAS_STAT", "SERN_NO", "DOC_NUMB", "EEDO_DESC", "FIRS_DATE", "FIRS_TIME", "EERR_DESC", "EERR_EERR_ID", "EEDO_ID", "EEDO_DATE", "EEDO_TIME", "MESSAGE_TYPE", "MESSAGE_NAME", "ETDO_ETDO_ID", "EPOL_EPOL_ID", "BEGIN_DATE", "ITEM_KEY", "EFUN_ID", "EFUN_DESC", "EPRO_ID", "EPRO_DESC", "CONF_TYPE", "RECIPIENT_ROLE", "NOT_ID", "STAT", "EANA_EANA_ROW", "OUT_FUNC", "END_DATE", "EITY_EITY_ID", "EIDR_VALUE", "EERR_DESC2", "EANA_DESC", "ETYI_ETYI_ID", "ANPT_ANPT_ID", "MESSAGE_BODY") AS 
  SELECT EPOL_NAME,
    d.ORGA_CODE,
    EPIU_ID,
    c.EINS_EINS_ID EINS_EINS_ID,
    c.CODE_DISP CODE_DISP,
    c.EUNL_EUNL_ID EUNL_EUNL_ID,
    c.EARD_EARD_ID EARD_EARD_ID,
    OUIN_TYPE,
    EPIU_TYPE,
    CODE_NAME,
    c.ETEX_ETEX_ID ETEX_ETEX_ID,
    PHAS_TYPE,
    PHAS_STAT,
    SERN_NO,
    DOC_NUMB,
    EEDO_DESC,
    FIRS_DATE,
    FIRS_TIME,
    g.EERR_DESC,
    b.EERR_EERR_ID EERR_EERR_ID,
    EEDO_ID,
    EEDO_DATE,
    EEDO_TIME,
    MESSAGE_TYPE,
    h.MESSAGE_NAME MESSAGE_NAME,
    a.ETDO_ETDO_ID ETDO_ETDO_ID,
    a.EPOL_EPOL_ID EPOL_EPOL_ID,
    FARSI_DATE_U(h.BEGIN_DATE) BEGIN_DATE,
    h.ITEM_KEY,
    pf.EFUN_ID,
    pf.EFUN_DESC,
    pr.EPRO_ID,
    pr.EPRO_DESC,
    CONF_TYPE,
    h.RECIPIENT_ROLE,
    h.not_id,
    h.stat,
    a.eana_eana_row,
    a.OUT_FUNC,
    a.END_DATE,
    EXP_EITEM_DOC_VALUE.EITY_EITY_ID,
    EXP_EITEM_DOC_VALUE.EIDR_VALUE,
    EXP_ERROR_INST2.EERR_DESC EERR_DESC2,
    EXP_ANALYZOR_EVENT.EANA_DESC,
    EXP_INSTRUMENT.ETYI_ETYI_ID,
    a.anpt_anpt_id,
    MESSAGE_BODY
  FROM EXP_EXPI_DOC a,
    EXP_EDOC_INSTRU b,
    EXP_POST_LINE_INSTRU c,
    EXP_POST_LINE d ,
    EXP_ERROR_INST g,
    WF_NOTE_V h ,
    EXP_PFUNCTION pf,
    EXP_PROGRAM pr,
    EXP_EITEM_DOC_VALUE EXP_EITEM_DOC_VALUE,
    EXP_INSTRUMENT EXP_INSTRUMENT,
    EXP_ERROR_INST EXP_ERROR_INST2,
    EXP_ANALYZOR_EVENT EXP_ANALYZOR_EVENT
  WHERE a.EEDO_ID    =b.EEDO_EEDO_ID
  AND b.EPIU_EPIU_ID =c.EPIU_ID
  AND a.EPOL_EPOL_ID =d.EPOL_ID
  AND b.EERR_EERR_ID =g.EERR_ID(+)
  AND pf.EFUN_ID(+)              = a.EFUN_EFUN_ID
  AND pf.EPRO_EPRO_ID            = pr.EPRO_ID(+)
  AND a.EEDO_ID                  =SUBSTR( h.ITEM_KEY,20,LENGTH(ITEM_KEY)-19)
  AND h.message_type             ='FLW_DEFE'
  AND a.EEDO_ID                  =EXP_EITEM_DOC_VALUE.EEDO_EEDO_ID
  AND c.EINS_EINS_ID             =EXP_INSTRUMENT.EINS_ID
  AND EXP_ERROR_INST2.EERR_ID    =b.EERR_EERR_ID_R1
  AND EXP_ANALYZOR_EVENT.EANA_ROW(+)=a.EANA_EANA_ROW
;
